#!/bin/bash
GR='\033[0;32m'
NC='\033[0m'

source /home/eclips/tools2/main

repo=(${repos[KMD]})
printf "\n${GR}>>> CHECKING KOMODO${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8 || { git clean -fdx && cp ../dPoW/iguana/pubkey.txt src/ && ./zcutil/build.sh -j8; }

repo=(${repos[CHIPS]})
printf "\n${GR}>>>>>>> CHECKING CHIPS${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8

repo=(${repos[GAME]})
printf "\n${GR}>>>>>>> CHECKING GAME${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8

repo=(${repos[HUSH3]})
printf "\n${GR}>>>>>>> CHECKING HUSH3${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8 || { git clean -fdx && ./zcutil/build.sh -j8; }

repo=(${repos[EMC2]})
printf "\n${GR}>>>>>>> CHECKING EMC2${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8

repo=(${repos[AYA]})
printf "\n${GR}>>>>>>> CHECKING AYA${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8

repo=(${repos[MCL]})
printf "\n${GR}>>>>>>> CHECKING MCL${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8

repo=(${repos[VRSC]})
printf "\n${GR}>>>>>>> CHECKING VERUS${NC}\n"
cd ${repo[0]} && git checkout ${repo[2]} && git pull && make -j8 || { ./zcutil/build.sh -j8; }

printf "\n"
