#!/bin/bash
coinlist=(
'CHIPS $HOME/chips3/src/chips-cli $HOME/chips3/src/chipsd .chips rescan chipsd.pid'
'GAME $HOME/GameCredits/src/gamecredits-cli $HOME/GameCredits/src/gamecreditsd .gamecredits newaddress gamecredits.pid'
'EMC2 $HOME/einsteinium/src/einsteinium-cli $HOME/einsteinium/src/einsteiniumd .einsteinium newaddress einsteinium.pid'
'GIN $HOME/gincoin-core/src/gincoin-cli $HOME/gincoin-core/src/gincoind .gincoincore newaddress gincoind.pid'
'HUSH3 $hushcli $hushd .komodo/HUSH3 kmd komodod.pid'
)
