#!/bin/bash
coinlist=(
'CHIPS chips-cli chipsd .chips rescan chipsd.pid'
'GAME gamecredits-cli gamecreditsd .gamecredits newaddress gamecredits.pid'
'EMC2 einsteinium-cli einsteiniumd .einsteinium newaddress einsteinium.pid'
'GIN gincoin-cli gincoind .gincoincore newaddress gincoind.pid'
'HUSH3 hush-cli hushd .komodo/HUSH3 kmd komodod.pid'
)
