#!/bin/bash
# functions file for nntools
#
# @author webworker01
#
timeSince () {
    local currentimestamp=$(date +%s)
    local timecompare=$1
    
    token=736082262:AAEehJ1CVJ-g2_a9BpCz97PfY6WjFv0OdtM # your telegram bot token
    chat_id=0 # telegram chat_id to report

    if [ ! -z $timecompare ] && [[ $timecompare != "null" ]]
    then
        local t=$((currentimestamp-timecompare))

        local d=$((t/60/60/24))
        local h=$((t/60/60%24))
        local m=$((t/60%60))
        local s=$((t%60))
        
        if (( h > 1 || d > 1 )); then
            curl -X POST -s $proxy "https://api.telegram.org/bot$token/sendMessage" -d "chat_id=$chat_id&parse_mode=HTML&text=test" > /dev/null
        fi
        
        if (( d > 0 )); then
            echo -n "${d}D"
        fi
        if (( d < 2 && h > 0 )); then
            echo -n "${h}h"
        fi
        if (( d == 0 && h < 4 && m > 0 )); then
            echo -n "${m}m"
        fi
        if (( d == 0 && h == 0 && m == 0 )); then
            echo -n "${s}s"
        fi

    fi
}
