#!/bin/bash

#imports
source /home/eclips/install/repos
source /home/eclips/install/functions
source /home/eclips/tools2/coinlist
source /home/eclips/.bash_profile

#defaults
addnodes=${addnodes:="-addnode=seed.komodostats.com -addnode=seed.webworker.sh"}
datetime=${datetime:=$(date '+%Y-%m-%d %H:%M:%S')}
dpowseeds=${dpowseeds:=('95.213.238.100' '77.75.121.138' '103.6.12.105' '139.99.209.214')}
