#!/bin/bash
# Used to define paths for coin daemons
#
# @author webworker01
#

#declare non komodo clis - set the full path accessible as the second part of each string, the 3rd entry is the name of the data dir for the coin and assumes they are in $HOME
coinsfirst=(
'BTC bitcoin-cli $HOME/bitcoin/src/bitcoind ../../bitcoin/'
)

coinsthird=(
'CHIPS $HOME/chips3/src/chips-cli $HOME/chips3/src/chipsd .chips'
'GAME $HOME/game/src/gamecredits-cli $HOME/game/src/gamecreditsd .gamecredits'
'EMC2 $HOME/einsteinium/src/einsteinium-cli $HOME/einsteinium/src/einsteiniumd .einsteinium'
'GIN $HOME/gincoin/src/gincoin-cli $HOME/gincoin/src/gincoind .gincoincore'
)
