#!/bin/bash
#update
#/home/eclips/tools2/checkpull
#kill
/home/eclips/tools2/pkill

started=0
while [[ ${started} -eq 0 ]]; do
  #start
  /home/eclips/tools2/start
  sleep 40
  #komodo-cli getbalance > /dev/null 2>&1 && gamecredits-cli getbalance > /dev/null 2>&1 && einsteinium-cli getbalance > /dev/null 2>&1 && gincoin-cli getbalance > /dev/null 2>&1 && chips-cli getbalance > /dev/null 2>&1 && hush-cli getbalance > /dev/null 2>&1
  komodo-cli getbalance > /dev/null 2>&1
  outcome=$(echo $?)
  if [[ ${outcome} -eq 0 ]]; then
    started=1
  fi
done
#iguana
/home/eclips/tools2/otary
sleep 120
/home/eclips/mine.sh &
